bar_components:
  default: >-
    [{"component_name":"bars-custom-html","route":"homepage","position":"left", "params": [{"name":"content","value":"<div class='bars-big-letter'>A</div>"}]},
     {"component_name":"bars-custom-html","route":"homepage","position":"left", "params": [{"name":"content","value":"<div class='bars-big-letter'>B</div>"}]},
     {"component_name":"bars-custom-html","route":"homepage","position":"right", "params": [{"name":"content","value":"<div class='bars-big-letter'>C</div>"}]},
     {"component_name":"bars-custom-html","route":"homepage","position":"right", "params": [{"name":"content","value":"<div class='bars-big-letter'>D</div>"}]},
     {"component_name":"bars-custom-html","route":"homepage","position":"centre", "params": [{"name":"content","value":"<div class='bars-big-letter'>E</div>"}]},
     {"component_name":"bars-custom-html","route":"homepage","position":"centre", "params": [{"name":"content","value":"<div class='bars-big-letter'>F</div>"}]},
     {"component_name":"bars-custom-html","route":"homepage","position":"top", "params": [{"name":"content","value":"<div class='bars-big-letter'>G</div>"}]},
     {"component_name":"bars-custom-html","route":"homepage","position":"top", "params": [{"name":"content","value":"<div class='bars-big-letter'>H</div>"}]},
     {"component_name":"bars-custom-html","route":"discovery","position":"left", "params": [{"name":"content","value":"<div class='bars-big-letter'>A</div>"}]},
     {"component_name":"bars-custom-html","route":"discovery","position":"left", "params": [{"name":"content","value":"<div class='bars-big-letter'>B</div>"}]},
     {"component_name":"bars-custom-html","route":"discovery","position":"right-alt", "params": [{"name":"content","value":"<div class='bars-big-letter'>C</div>"}]},
     {"component_name":"bars-custom-html","route":"discovery","position":"right-alt", "params": [{"name":"content","value":"<div class='bars-big-letter'>D</div>"}]},
     {"component_name":"bars-custom-html","route":"discovery","position":"top", "params": [{"name":"content","value":"<div class='bars-big-letter'>E</div>"}]},
     {"component_name":"bars-custom-html","route":"discovery","position":"top", "params": [{"name":"content","value":"<div class='bars-big-letter'>F</div>"}]},
     {"component_name":"bars-custom-html","route":"topic","position":"right", "params": [{"name":"content","value":"<div class='bars-big-letter'>G</div>"}]},
     {"component_name":"bars-custom-html","route":"topic","position":"right", "params": [{"name":"content","value":"<div class='bars-big-letter'>H</div>"}]},
     {"component_name":"bars-custom-html","route":"topic","position":"top", "params": [{"name":"content","value":"<div class='bars-big-letter'>I</div>"}]},
     {"component_name":"bars-custom-html","route":"categories","position":"left", "params": [{"name":"content","value":"<div class='bars-big-letter'>K</div>"}]},
     {"component_name":"bars-custom-html","route":"category","position":"left", "params": [{"name":"content","value":"<div class='bars-big-letter'>L</div>"}]},
     {"component_name":"bars-custom-html","route":"tag","position":"right", "params": [{"name":"content","value":"<div class='bars-big-letter'>M</div>"}]}]
  json_schema: >-
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "component_name": {
            "type": "string"
          },
          "route": {
            "type": "string"
          },
          "position": {
            "type": "string"
          },
          "params": {
            "type": "array",
            "format": "table",
            "uniqueItems": true,
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  description: "Specify Component, Route and Position.  Order determines layout. <br/><br/>Route must be either: discovery, topic, tag, category OR categories.  <br/><br/>Position must be either: top, left, right OR right-alt."
sidebars_minimised_by_default:
  type: list
  default: ""
  description:
    en: "The sidebars that are minimised by default.  Can be one of top|left|right|right-alt."
left_sidebar_width:
  default: 300
right_sidebar_width:
  default: 300
sticky_sidebars:
  default: true
sidebar_sticky_top_position:
  default: 60
sidebar_height:
  default: 800
scrolly_sidebars:
  default: false
top_bar_height:
  default: 150
top_bar_sticky_top_position:
  default: 60
sidebar_gap:
  default: 5
rightalt_sidebar_gap:
  default: 5
sidebar_between_component_gap:
  default: 20
sidebars_collapsible:
  default: true
sidebars_dismisable:
  default: true